const mongoose = require('mongoose');

const assignmentSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    assignedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    topic: { type: String, required: true },
    title: { type: String, required: true },
    description: { type: String, default: '' },
    subject: { type: String, default: 'General' },
    difficulty: { type: String, enum: ['novice', 'professional', 'expert'], default: 'professional' },
    tasks: { type: [String], default: [] }, // Specific steps generated by AI
    duration: { type: Number, default: 30 }, // minutes
    startedAt: { type: Date },
    content: { type: String, default: '' }, // text submission
    feedback: { type: String, default: '' },
    grade: { type: String, default: '' },
    score: { type: Number, default: null },
    status: {
      type: String,
      enum: ['pending', 'submitted', 'graded'],
      default: 'pending',
    },
    strengths: { type: [String], default: [] },
    improvements: { type: [String], default: [] },
    analysis: {
      technicalAccuracy: Number,
      completeness: Number,
      clarity: Number
    },
    wrongAnswers: [{
      task: String,
      mistake: String,
      correctSolution: String
    }],
    dueDate: { type: Date },
    submittedAt: { type: Date },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Assignment', assignmentSchema);
